import 'package:flutter/material.dart';
import 'package:recipe/utils/class.dart';

class Local {
  static List<LocalRecipe> localrecipes = [
    LocalRecipe(
        id: '1',
        title: 'Egusi Soup',
        time: '30',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/egusisoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '200', percent: 0.7),
          Nutrients(name: 'Protein', weight: '10gm', percent: 0.5),
          Nutrients(name: 'Carb', weight: '50gm', percent: 0.9),
        ],
        steps: [
          " Add palm oil, blended white-melon seeds(egusi) and 1/4 cup water into a large pot and place on medium heat.",
          "Next, add blended onions and pepper purée.",
          "Mix thoroughly to combine and fry for about 10 minutes, staring occasionally.",
          "Fry till you can literally see the palm oil simmering at the top and there are no more traces of water.",
          "Next, add meat stock, stir and leave to cook for one minute.",
          "Then add cooked goat meat, beef, cow skin(kpomo) and tripe(shaki).",
          "Add 3 cups water, then stir to combine and bring to a light boil.",
          "Then add opeyi (local seasoning). This is totally optional.",
          "The crayfish, seasoning cubes, ground pepper and salt go in next. Stir to combine and leave to cook for 5 minutes.",
          "Then add shredded stock fish and dry fish, stir to combine.",
          "Leave to cook for 10 more minutes.",
          "Finally, add shredded pumpkin leaves (ugu).",
          "Stir one last time and take off heat immediately.",
        ],
        ingredients: [
          "1 cup palm Oil",
          "3 cups ground white-seed melon(egusi)",
          "1/4 cup water",
          "5 yellow peppers(blended)",
          "5 fresh red peppers(blended)",
          "1 large onion bulb(blended)",
          "1 cup meat stock (liquid gotten after cooking the meat)",
          "Cow skin (Kpomo, pre-cooked)",
          "Goat meat(pre-cooked)",
          "Tripe(shaki, pre-cooked)",
          "Beef(pre-cooked)",
          "3 cups water",
          "1/8 teaspoon opeyi (local seasoning) – optional",
          "2 table spoons crayfish",
          "1/2 table spoon ground pepper",
          "3 seasoning cubes",
          "Salt",
          "1 cup shredded stock fish",
          "1 cup shredded dry Fish",
          "1 full bunch pumpkin Leaves (Ugu)"
        ]),
    LocalRecipe(
        id: '2',
        title: 'Afang Soup',
        time: '20',
        color: Color(0xffEACBCB),
        imageUrl: 'assets/images/afangsoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '200', percent: 0.7),
          Nutrients(name: 'Protein', weight: '10gm', percent: 0.5),
          Nutrients(name: 'Carb', weight: '50gm', percent: 0.9),
        ],
        steps: [
          " Boil the meats on high heat, starting with the toughest meats first, offal may be boiled separately if they are bloody. Add seasoning cubes, onions are optional. when the meats are soft, add the smoked fish and continue to boil till very soft.",
          "While the meats are cooking, get the leaves ready.",
          "Slice and wash the water leaves with salts to remove all traces of dirt. Also wash and soak the Okazi/Afang leaves in hot water for 2 minutes. This process will help soften Afang leaves.",
          "Then transfer the Afang leaves into a blender, add a small amount of water, then blend to your preferred consistency. You may also pound or grind the Afang leaves.",
          "Soak the smoked catfish in hot water, clean to remove traces of dirt then shred and set aside.",
          "When the meats are well cooked, you should end up with 1-2 cups of stock. To this, add crayfish, blended pepper, smoked fish, smoked prawns, seasoning cubes, periwinkles. Leave to cook for 3-5 minutes.",
          "Now, add the washed water leaves, stir and combine. Then leave to cook for 2-3 minutes. The water leaves will wilt in the soup as it’s got quite a lot of water contents, don’t  be tempted to add much. Remember we’ll be adding afang leaves.",
          "Now, add palm oil, stir and combine, leave to cook for 3 minutes.",
          "Add the blended okazi/afang leaves, stir and combine, leave to cook for 5 minutes or until leaves are tender enough for you, Taste for seasoning at this time and adjust if necessary.",
          "Switch the heat off and let it simmer with the residual heat for another 2 minutes.",
          "It’s ready, enjoy with any swallow of your choice."
        ],
        ingredients: [
          " 1kg of assorted meats (Beef, Smoke fish, Turkey, Goat meat, Tripe(shaki), Cow skin(ponmo, Cow legs are ideal)",
          "4 bunches of water leave ",
          "3 cups of Okazi/Afang leaves",
          "2 cooking spoons of palm oil",
          "2 pieces of smoked fish",
          "3 pieces of stock fish  ",
          "2 cups of periwinkles with or without shells on ",
          "1 cooking spoons of fresh grounded scotch bonnet pepper",
          "1 cooking spoon of crayfish ",
          "4 seasoning cubes",
          "Salt to taste",
        ]),
    LocalRecipe(
        id: '3',
        title: 'Okra Soup',
        time: '40',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/okrosoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '100', percent: 0.2),
          Nutrients(name: 'Protein', weight: '10gm', percent: 0.7),
          Nutrients(name: 'Carb', weight: '50gm', percent: 0.6),
          Nutrients(name: 'Fat', weight: '10gm', percent: 0.3),
        ],
        steps: [
          " Thoroughly wash goat meat, cow skin (kpomo) and tripe(shaki) with tap water. Season with 1 onion, 3 seasoning cubes, 1/2 table spoon ground pepper and salt. Add 1-2 cups of water, mix thoroughly. Set on medium heat and cook till tender.",
          "Thoroughly wash stock fish and dry fish, first with hot water and afterwards with tap water. You may need to further boil your stock fish depending on its toughness. Your stock fish should be very tender.",
          "Blend remaining onion, yellow peppers and red peppers with an electric blender till a puree is formed.",
          "In another pot, add palm oil, set on medium for 10 seconds or until the palm oil is fully liquid then add diced onions and sauté for 30-45 seconds.",
          "Next, add the crayfish, remaining seasoning cubes, stir to combine.",
          "Next add 2 cups of meat stock and some more water if the meat stock isn’t enough. Bring to a light simmer for about 2-3 minutes.",
          "After that you add the open, ground pepper, stock fish, dry fish, chopped yellow and red pepper and the cooked meat. Leave to simmer for 1 minute.",
          "Next, add the chopped okra, stir to combine and leave to cook for another minute.",
          "Sprinkle some salt for taste and add chopped pumpkin leaves (ugu), stir to combine and turn off heat immediately."
        ],
        ingredients: [
          "2 cups chopped okra",
          "1/2 cup palm oil",
          "Goat meat",
          "kpomo (Cow skin)",
          "Smoked fish",
          "Stock fish",
          "1/4 teaspoon opeyi (local seasoning) (optional)",
          "6 seasoning cubes",
          "2 medium onion bulbs",
          "5 pcs fresh red pepper",
          "5 pcs fresh yellow pepper",
          "1 table spoon crayfish",
          "1 cup chopped pumpkin (ugu) leaves",
          "1 table spoon ground pepper",
          "Salt to taste"
        ]),
    LocalRecipe(
        id: '4',
        title: 'Ogbono Soup',
        time: '30',
        color: Color(0xffF69383),
        imageUrl: 'assets/images/ogbonosoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '200', percent: 0.7),
          Nutrients(name: 'Protein', weight: '10gm', percent: 0.5),
          Nutrients(name: 'Carb', weight: '50gm', percent: 0.9),
        ],
        steps: [
          " Thoroughly wash goat meat, beef, kpomo and shaki with tap water. Season with 1 onion, 3 seasoning cubes, 1/2 table spoon ground pepper and salt. Add 1-2 cups of water, mix thoroughly. Set on medium heat and cook till tender.",
          "Thoroughly wash stock fish and dry fish, first with hot water and afterwards with tap water. You may need to further boil your stock fish depending on its toughness. Your stock fish should be very tender.",
          "Blend remaining onion, yellow peppers and red peppers with an electric blender till a puree is formed.",
          "In another pot, add grounded ogbono and palm oil, set on medium for 10 seconds or until the palm oil is fully liquid then add blended pepper puree, stir to combine.",
          "Next stir in the cooked meat and meat stock and leave to simmer for 5 minutes. You can choose to add more water if the meat stock is not a lot (depending on how thick you want the soup to be).",
          "Add remaining seasoning cubes, crayfish, ground pepper, dry fish, stock fish, opeyi and salt. Leave to cook for about 20-25minutes on medium heat.",
          "Next add chopped okro and leave to cook for another 3mins",
          "Finally add chopped pumpkin leaves (ugu), stir to combine and turn off heat immediately."
        ],
        ingredients: [
          "1 cup ground ogbono",
          "1/2 cup palm oil",
          "Goat meat",
          "Beef",
          "Cow skin(kpomo)",
          "Smoked fish",
          "Stock fish",
          "1/4 teaspoon opkehe (local seasoning) (optional)",
          "6 seasoning cubes",
          "2 medium onion bulbs",
          "5 pcs fresh red pepper",
          "5 pcs fresh yellow pepper",
          "2 table spoons crayfish",
          "2 cup chopped okras",
          "1 cup chopped pumpkin (ugu) leaves",
          "1 table spoon ground pepper",
          "Salt to taste",
        ]),
    LocalRecipe(
        id: '5',
        title: 'Banga Soup',
        time: '20',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/bangasoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '100', percent: 0.4),
          Nutrients(name: 'Protein', weight: '10gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '50gm', percent: 0.8),
          Nutrients(name: 'Fat', weight: '10gm', percent: 0.5),
        ],
        steps: [
          " Boil goat meat and tripe (shaki) on medium-high heat. Add 2 seasoning cubes, ½ tablespoon dry pepper and salt to taste. Leave to cook till tender. If Kpomo is tough, cook with shaki and goat meat. When all the meats are tender, separate meat and stock, set aside.",
          "Blend scotch Bonnet and Ogiri with a blender until a smooth paste is formed. You can add a little water to make the blending process easier.",
          "Place a big pot on the hob, Add the palm kernel extract, then add the stock from the meats. If your stock isn’t enough, add water, you’ll need the consistency to be quite fluid; a semi thick consistency. Bring to a light simmer.",
          "Add blended pepper mix, shredded stock fish, shredded dry fish and cooked meat to the pot. Stir to combine and leave to cook for 5 minutes.",
          "Next add remaining seasoning cubes, ground crayfish, ground pepper and salt to taste; stir and leave to cook for another 5 minutes.",
          "Finally, add scent leaves (efinrin), stir to combine and take off heat immediately."
        ],
        ingredients: [
          "6 cups palm kernel extract",
          "Goat meat",
          "Tripe (shaki)",
          " Cow skin (kpomo)",
          "2 cups shredded stock fish",
          "1 cup shredded dry fish",
          "½ cups scent leaves (efinrin leaves)",
          "2 tablespoons ground crayfish",
          "4 seasoning cubes",
          "1/8 teaspoon okpehe",
          "4 scotch bonnet/fresh pepper pepper (atarodo)",
          "1 tablespoon grounded pepper",
          "Salt"
        ]),
    LocalRecipe(
        id: '6',
        title: 'Fried Rice',
        time: '30',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/friedrice.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '140', percent: 0.5),
          Nutrients(name: 'Protein', weight: '14gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '60gm', percent: 0.9),
          Nutrients(name: 'Fat', weight: '40gm', percent: 0.6),
        ],
        steps: [
          "Wash rice thoroughly and per boil with 3 cups chicken stock and one table spoon curry powder. Cook till it is 95% done. You can use home-made chicken stock or store bought chicken stock. You can use water in place of chicken stock.",
          "When rice is cooked, place in a colander and set aside.",
          "Place chicken drumsticks in a Tupperware.",
          "Add 2 table spoons roasted meat(suya) spice, 1 seasoning cube, 1 tablespoon vegetable oil, 1/2 teaspoon thyme, and a pinch of salt.",
          "Mix thoroughly, cover the Tupperware and place in the fridge. Leave to marinade for at least one hour. The longer the marinade, the better. To marinade is optional though.",
          "Grill chicken drumsticks in the oven for 45 minutes at 350 degrees Fahrenheit. Alternatively, you can fry it with vegetable oil if you do not have an oven.",
          "In a large pot, heat up vegetable oil on medium heat.",
          "Sauté diced onions for 1 minute.",
          "Add minced garlic and sauté till fragrant.",
          "Add carrots and sauté for one minute.",
          "Add red bell pepper, continue to stir fry until crisp-tender.",
          "Stir in boiled basmati rice, mix thoroughly to combine.",
          "Add soy sauce and oyster sauce, remaining seasoning cubes, thyme, curry powder, fried rice spice and salt to taste.",
          "Stir thoroughly to combine all ingredients, leave to simmer for 5mins.",
          "Stir in spring onions and turn off heat immediately."
        ],
        ingredients: [
          "2 cups of rice",
          "3 cups chicken stock",
          "Chicken",
          "4 seasoning cubes",
          "1 medium onion bulb (finely diced)",
          "1 large carrots (finely diced)",
          "1 red bell pepper (finely diced)",
          "1 green bell pepper (finely diced)",
          "1 bunch spring onions (shredded)",
          "100g sweet corn",
          "2 table spoons roasted meat(suya) spice",
          "2 tablespoons soy sauce",
          "2 tablespoons oyster sauce",
          "1 table spoon fried rice spice",
          "2 teaspoons thyme",
          "3 teaspoons curry powder",
          "1 large onion bulb",
          "4 garlic cloves, minced",
          "Salt",
          "1 cooking spoon vegetable oil",
        ]),
    LocalRecipe(
        id: '7',
        title: 'Jollof Rice',
        time: '30',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/bangasoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '140', percent: 0.5),
          Nutrients(name: 'Protein', weight: '14gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '60gm', percent: 0.9),
          Nutrients(name: 'Fat', weight: '40gm', percent: 0.6),
        ],
        steps: [
          " precook your rice for 10 minutes",
          "Wash rice thoroughly, set aside.",
          "Blend fresh tomatoes, fresh pepper, garlic and one onion altogether using a blending machine till a smooth puree is formed. Add a little water to make blending process easy.",
          "Afterwards, heat up 2 cooking spoons of vegetable oil into the pot, chop the remaining onion bulb and transfer to hot oil, sauté for 45seconds until translucent.",
          "Next add tomato paste and leave to fry for another 5minutes, stir occasionally.",
          "Next, transfer blended puree and leave to fry for about 5-10 minutes, stirring occasionally to prevent burning. You will know its perfected fried when oil sits on top of the puree.",
          "Add 2 cups of chicken stock (or water if you don’t have chicken stock) into your fried puree.",
          "Next, add curry powder, thyme, seasoning cubes, grounded pepper, crayfish and salt to taste. Stir to combine all ingredients.",
          "Stir in the pre-cooked rice, make sure the rice is fully coated with the sauce.",
          "Add nutmeg and stir to combine.",
          "Next gently slip in bay leaves into the rice.",
          "Cut foil paper and use it to cover the rice before putting the lid of the pot.",
          "Cook for 15 minutes or until rice is properly cooked.",
          "Remove lid and foil when rice is cooked and stir thoroughly to combine all ingredients.",
          "Remove the heat and all to cool down by covering the pot halfway with the lid.",
          "You can serve jollof rice with any meat or fish of your choice."
              "Note – Using the foil paper helps trap the steam inside the pot and this will make the rice become soft faster and will prevent it from getting soggy and meshed up. The grains will stand separately. It is not water that makes the rice soft, it is steam. So you don’t need to add more water.",
        ],
        ingredients: [
          "  2 cups of rice",
          "2 fresh tomatoes",
          "3 red bell peppers (tatashe)",
          "3 fresh peppers",
          "3 table spoons of tomato paste (canned tomato)",
          "1 cooking spoon of vegetable oil",
          "2 medium onion bulbs",
          "4 cloves of garlic",
          "1 teaspoon of thyme",
          "5 seasoning cubes",
          "2 teaspoons of grounded crayfish",
          "1 teaspoon of nutmeg",
          "  1 teaspoon of grounded pepper",
          "6 bay leaves (optional)",
          "2 Chicken stock",
          "½ teaspoon of salt.",
          "Foil paper",
        ]),
    LocalRecipe(
        id: '8',
        title: 'Ofada Rice',
        time: '10',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/ofadariceandstew.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '140', percent: 0.5),
          Nutrients(name: 'Protein', weight: '14gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '60gm', percent: 0.9),
          Nutrients(name: 'Fat', weight: '40gm', percent: 0.6),
        ],
        steps: [
          " Thoroughly wash beef, tripe(shaki), goat meat and cow skin (kpomo, remember to cut them into tiny pieces). Place in a medium pot, season with half of the onion, 3 seasoning cubes, ground pepper and salt to taste. Stir thoroughly to combine and leave to cook on medium heat for 25-30mins or until tender.",
          "While that is cooking, wash the red bell peppers and fresh peppers, ridding them of the seeds, (leave the seeds if you want the stew very peppery), place in a baking tray. At this point you can either choose to wait for the meat to get soft so that you can grill it while the peppers are roasting or go ahead and place the peppers in the oven and fry your meat when it is soft. Set the oven to 160 degree centigrade and roast for 40mins.",
          "When peppers are perfectly roasted, place in a blender or food processor and blitz on medium heat for 20 seconds or until a very rough consistency is formed. Set aside.",
          "Pour palm oil into a pot and set on low heat. Leave to bleach for about 10mins",
          "Slice remaining onions and add into hot oil. Sauté till caramelized, this should take at most 15mins. Remember, your heat should be turned down to the lowest to prevent the onions from burning. Stir occasionally.",
          "Afterwards, add locust beans (iru) and ground crayfish, stir and leave to cook for one minute.",
          "Add blended peppers, stir thoroughly to combine. At this point you can turn up the heat to medium. Leave to fry for about 5 minutes, staring occasionally.",
          "Next add 1 cup of meat stock (water used to cook the meat), remaining seasoning cubes and salt to taste. Leave to cook for 5-7mins.",
          "Finally, add the grilled or fried pieces of meat and stir thoroughly to combine. Leave to cook for another 5mins and turn off heat afterwards.",
          "Wash rice thoroughly or until water runs clear."
              "Add rice to boiling water and leave to cook for about 10mins on medium heat. Do not cover your pot at this time."
              "After per-boiling, wash rice again thoroughly."
              "Add 2 cups of water to a pot and bring to a boil. Add washed rice and leave to cook till tender. Remember to leave your pot open to prevent sogginess."
              "When rice is properly cooked, serve with ofada stew."
        ],
        ingredients: [
          " 2 cups ofada rice",
          "10 large red bell peppers (tatashe)",
          "5 medium fresh peppers (atarodo)",
          "Beef",
          "Tripe(shaki)",
          "Goat meat",
          "Cow skin (kpomo)",
          "1 large onion bulb",
          "2 table spoons crayfish",
          "4 seasoning cubes",
          "1 table spoon ground pepper",
          "2 table spoons locust beans (iru)",
          "1 cup shredded dry fish",
          "1 cup palm oil",
          "Salt to taste",
        ]),
    LocalRecipe(
        id: '9',
        title: 'Coconut Rice',
        time: '10',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/coconotjellofrice.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '140', percent: 0.5),
          Nutrients(name: 'Protein', weight: '14gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '60gm', percent: 0.9),
          Nutrients(name: 'Fat', weight: '40gm', percent: 0.6),
        ],
        steps: [
          "  Wash rice thoroughly, set aside and let dry.",
          "Add butter into a pot, add rice stir till rice is brown and set aside.",
          "Blend fresh tomatoes, fresh pepper, garlic and one onion altogether using a blending machine till a smooth puree is formed. Add a little water to make blending process easy.",
          "Afterwards, heat up 2 cooking spoons of vegetable oil into the pot, chop the remaining onion bulb and transfer to hot oil, sauté for 45seconds until translucent.",
          "Stir ",
          "Next add tomato paste and leave to fry for another 5minutes, stir occasionally.",
          "Next, transfer blended puree and leave to fry for about 5-10 minutes, stirring occasionally to prevent burning. You will know its perfected fried when oil sits on top of the puree.",
          "Add chicken stock and coconut milk (or water if you don’t have chicken stock) into your fried puree.",
          "Next, add curry powder, thyme, seasoning cubes, grounded pepper, crayfish and salt to taste. Stir to combine all ingredients.",
          "Stir in the rice, make sure the rice is fully coated with the sauce.",
          "Next gently slip in bay leaves into the rice.",
          "Cut foil paper and use it to cover the rice before putting the lid of the pot",
          "Remove lid and foil when rice is cooked, add a teaspoon of butter and leave on fire for few minutes",
          "Stir thoroughly to combine all ingredients.",
          "Remove the heat."
              "Note – Using the foil paper helps trap the steam inside the pot and this will make the rice become soft faster and will prevent it from getting soggy and meshed up. The grains will stand separately. It is not water that makes the rice soft, it is steam. So you don’t need to add more water."
        ],
        ingredients: [
          "2 cups of rice",
          "2 fresh tomatoes",
          "Coconut milk",
          "3 red bell peppers (tatashe)",
          "3 fresh peppers",
          "3 table spoons of tomato paste",
          "1 cooking spoon of vegetable oil",
          "2 medium onion bulbs",
          "4 cloves of garlic",
          "1 teaspoon of thyme",
          "5 seasoning cubes",
          "2 teaspoons of grounded crayfish",
          "1 teaspoon of nutmeg",
          "1 teaspoon of grounded pepper",
          "6 bay leaves (optional)",
          "2 Chicken stock",
          "½ teaspoon of salt",
        ]),
    LocalRecipe(
        id: '10',
        title: 'Pepper Soup',
        time: '10',
        color: Color(0xffFBB97C),
        imageUrl: 'assets/images/goatmeatpeppersoup.jfif',
        nutrients: [
          Nutrients(name: 'Calories', weight: '140', percent: 0.5),
          Nutrients(name: 'Protein', weight: '14gm', percent: 0.9),
          Nutrients(name: 'Carb', weight: '60gm', percent: 0.9),
          Nutrients(name: 'Fat', weight: '40gm', percent: 0.6),
        ],
        steps: [
          "Wash the goat meat thoroughly with tap water to remove excess blood.",
          "Transfer to a medium size pot and place on medium heat.",
          "Add the onion, garlic, seasoning cubes and salt to taste, stir to combine and place the lid on the pot. Leave to simmer for 10 minutes. Do not add any water at this stage.",
          "Afterwards, add about 3-4 cups of water and leave to boil for another 10 minutes.",
          "Next, add the pepper soup spice, dry pepper and chopped fresh peppers and leave to boil for another 10-15 minutes or until goat meat is tender.",
          "Finally, add the scent(efirin) leaves and turn off heat immediately."
        ],
        ingredients: [
          "Goat meat small pieces",
          "1 medium onion(diced)",
          "3 garlic cloves(minced)",
          "2 seasoning cubes",
          "4 fresh red peppers(chopped)",
          "2 table spoons pepper-soup spice",
          "1 1/2 table spoons dry pepper",
          "5 scent(efirin) leaves(chopped)",
          "Salt to taste",
        ]),
  ];
}
